name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm test 2>result.txt
      - name: Send email, you star
              uses: dawidd6/action-send-mail@v1.3.0
              with:
                server_address: smtp.gmail.com
                server_port: 465
                username: jviejocodecripto@gmail.com
                password: ${{ secrets.GMAIL_PASS }}
                subject: Your a star ✨
                body: ${{ github.actor }} just starred your mail-on-star repo!!! ${{ github.repository }}
                to: ${{ secrets.GMAIL_ADDRESS }}
                from: ${{ secrets.GMAIL_ADDRESS }}